import '@radix-ui/themes/styles.css';
import './theme-config.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './NavBar'
import { Container, Theme } from '@radix-ui/themes';
import AuthProvider from './auth/Provider';
import QueryClientProvider from './QueryClientProvider';
import {WebSocketProvider} from "@/app/contexts/WebSocketContext";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <QueryClientProvider>
          <AuthProvider>
            <WebSocketProvider>
              <Theme appearance="light" accentColor="violet">
                <NavBar />
                <main className='p-5'>
                  <Container>
                    {children}
                  </Container>
                </main>
              </Theme>
            </WebSocketProvider>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  )
}
